# [START runtime]
runtime: python
env: flex
#entrypoint: gunicorn -b :$PORT django_school.wsgi
entrypoint: gunicorn -t 300 -b :$PORT django_school.wsgi


beta_settings:
  cloud_sql_instances: yantra-242714:asia-southeast1:yantraksh-webapp

runtime_config:
  python_version: 3
# [END runtime]


env_variables:
  DB_NAME: 'postgres'
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_HOST: '/cloudsql/yantra-242714:asia-southeast1:yantraksh-webapp'